//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fat.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.StockQuotes = new HashSet<StockQuote>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedUtcDate { get; set; }
        public Nullable<System.DateTime> ModifiedUtcDate { get; set; }
        public bool IsActive { get; set; }
        public string Industry { get; set; }
    
        public virtual ICollection<StockQuote> StockQuotes { get; set; }
    }
}
