//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fat.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQuote
    {
        public string Code { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public System.DateTime CreatedUtcDate { get; set; }
        public Nullable<System.DateTime> ModifiedUtcDate { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
